### ISSUE TITLE
Tip diversification rates

### ISSUE THREAD

**Issue by elizeng** [rsetienne/secsse#21]
I am wondering if there was an output or function within `secsse` to calculate the tip diversification rates?

And if so, would love some examples.

Thanks!

**Comment by rsetienne** [comment]
I saw this just now. There is no such function but given each tip state the
diversification rates are easily computed as lambda_i - mu_i where I is the
state of the tip and lambda and mu are the speciation and extinction rates.

Op do 18 jul. 2024 01:53 schreef Elize Ng ***@***.***>:
